[package]
name = "steemit-api"
version = "0.0.0"
authors = ["Thomas Heck <t@b128.net>"]

[dependencies]
futures = "0.1.18"
tokio-core = "0.1.12"
hyper = "0.11.17"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
hyper-tls = "0.1.2"
